apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snnamani/project-works.git
    targetRevision: HEAD
    path: project-works
  destination:
    server: https://kubernetes.default.svc
    namespace: projects
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
